#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Sep 11, 2020 09:17:46 PM EDT  platform: Windows NT
#
# May just use a webserver to constantly randomize
#
# pyinstaller randomize.py --onefile --add-data "C:\Users\Angel LaVoie\Downloads\BL3\StandaloneHotfixInjection\RandomizerPackage\utils\;utils" command to exe that bitch

import gen_skill_randomizer
import gen_spawn_randomizer
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    print('Starting Program...')
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def RandomizeEnemy():
    print('Randomize!')
    gen_spawn_randomizer.SpawnRandom()
    sys.stdout.flush()

def RandomizeSkill():
    print('Randomize!')
    gen_skill_randomizer.SkillRandom()
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import randomizewindow
    randomizewindow.vp_start_gui()




